repo_url: https://github.com/Augcamp/FCTE-Qualidade-de-Software-1
repo_name: FCTE-Qualidade-de-Software-1
site_name: Grupo Roberta Williams - Turma 2 (2025.1)
site_description: Documentação do projeto da dupla do grupo Roberta Williams de Qualidade de Software (2025.1), Turma 2
nav:
  - Home: index.md
  - Fase 1 - Propósito de Avalição: fase1.md

theme:
  name: material
  locale: pt_BR
  color_mode: auto
  user_color_mode_toggle: true 
  include_sidebar: true